if(NOT DEFINED YGGDRASIL_PROJECT_ROOT)
    message(FATAL_ERROR "YGGDRASIL_PROJECT_ROOT is required.")
endif()

if(NOT DEFINED YGGDRASIL_TEST_BINARY_DIR)
    message(FATAL_ERROR "YGGDRASIL_TEST_BINARY_DIR is required.")
endif()
