file(READ "${CMAKE_CURRENT_LIST_DIR}/../docs/SOURCES.json" YGGDRASIL_SOURCE_MANIFEST)

function(yggdrasil_sources out)
    string(JSON source_count LENGTH "${YGGDRASIL_SOURCE_MANIFEST}" sources)
    math(EXPR source_last "${source_count} - 1")
    set(sources)
    foreach(index RANGE ${source_last})
        string(JSON source MEMBER "${YGGDRASIL_SOURCE_MANIFEST}" sources ${index})
        list(APPEND sources "${source}")
    endforeach()
    set("${out}" "${sources}" PARENT_SCOPE)
endfunction()

function(yggdrasil_source out source field)
    string(JSON source_type TYPE "${YGGDRASIL_SOURCE_MANIFEST}" sources "${source}" "${field}")
    if(source_type STREQUAL "ARRAY")
        string(JSON source_length LENGTH "${YGGDRASIL_SOURCE_MANIFEST}" sources "${source}" "${field}")
        set(value)
        if(source_length)
            math(EXPR source_last "${source_length} - 1")
            foreach(index RANGE ${source_last})
                string(JSON item GET "${YGGDRASIL_SOURCE_MANIFEST}" sources "${source}" "${field}" ${index})
                list(APPEND value "${item}")
            endforeach()
        endif()
    else()
        string(JSON value GET "${YGGDRASIL_SOURCE_MANIFEST}" sources "${source}" "${field}")
    endif()
    set("${out}" "${value}" PARENT_SCOPE)
endfunction()
