set(PYYGGDRASIL_STUB_ROOT "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/pyyggdrasil")
set(PYYGGDRASIL_PRIVATE_STUB_ROOT "${PYYGGDRASIL_STUB_ROOT}/_pyyggdrasil")

function(pyyggdrasil_patch_stub_text PYYGGDRASIL_STUB_FILE)
    file(READ "${PYYGGDRASIL_STUB_FILE}" PYYGGDRASIL_STUB_CONTENT)
    set(PYYGGDRASIL_PATCHED_STUB_CONTENT "${PYYGGDRASIL_STUB_CONTENT}")

    string(REPLACE "pyyggdrasil._pyyggdrasil." "pyyggdrasil." PYYGGDRASIL_PATCHED_STUB_CONTENT "${PYYGGDRASIL_PATCHED_STUB_CONTENT}")
    string(REPLACE "pyyggdrasil._pyyggdrasil" "pyyggdrasil" PYYGGDRASIL_PATCHED_STUB_CONTENT "${PYYGGDRASIL_PATCHED_STUB_CONTENT}")

    if(NOT PYYGGDRASIL_STUB_CONTENT STREQUAL PYYGGDRASIL_PATCHED_STUB_CONTENT)
        file(WRITE "${PYYGGDRASIL_STUB_FILE}" "${PYYGGDRASIL_PATCHED_STUB_CONTENT}")
    endif()
endfunction()

if(EXISTS "${PYYGGDRASIL_STUB_ROOT}")
    if(IS_DIRECTORY "${PYYGGDRASIL_PRIVATE_STUB_ROOT}")
        file(GLOB_RECURSE PYYGGDRASIL_PRIVATE_STUB_FILES "${PYYGGDRASIL_PRIVATE_STUB_ROOT}/*.pyi")
        list(SORT PYYGGDRASIL_PRIVATE_STUB_FILES)

        foreach(PYYGGDRASIL_PRIVATE_STUB_FILE IN LISTS PYYGGDRASIL_PRIVATE_STUB_FILES)
            file(RELATIVE_PATH PYYGGDRASIL_RELATIVE_STUB_PATH "${PYYGGDRASIL_PRIVATE_STUB_ROOT}" "${PYYGGDRASIL_PRIVATE_STUB_FILE}")
            set(PYYGGDRASIL_PUBLIC_STUB_FILE "${PYYGGDRASIL_STUB_ROOT}/${PYYGGDRASIL_RELATIVE_STUB_PATH}")
            get_filename_component(PYYGGDRASIL_PUBLIC_STUB_DIR "${PYYGGDRASIL_PUBLIC_STUB_FILE}" DIRECTORY)
            get_filename_component(PYYGGDRASIL_PUBLIC_STUB_NAME_WE "${PYYGGDRASIL_PUBLIC_STUB_FILE}" NAME_WE)
            set(PYYGGDRASIL_PUBLIC_PACKAGE_DIR "${PYYGGDRASIL_PUBLIC_STUB_DIR}/${PYYGGDRASIL_PUBLIC_STUB_NAME_WE}")

            if(IS_DIRECTORY "${PYYGGDRASIL_PUBLIC_PACKAGE_DIR}")
                set(PYYGGDRASIL_PUBLIC_STUB_FILE "${PYYGGDRASIL_PUBLIC_PACKAGE_DIR}/__init__.pyi")
                set(PYYGGDRASIL_PUBLIC_STUB_DIR "${PYYGGDRASIL_PUBLIC_PACKAGE_DIR}")
            endif()

            file(MAKE_DIRECTORY "${PYYGGDRASIL_PUBLIC_STUB_DIR}")

            if(NOT EXISTS "${PYYGGDRASIL_PUBLIC_STUB_FILE}")
                file(READ "${PYYGGDRASIL_PRIVATE_STUB_FILE}" PYYGGDRASIL_PRIVATE_STUB_CONTENT)
                file(WRITE "${PYYGGDRASIL_PUBLIC_STUB_FILE}" "${PYYGGDRASIL_PRIVATE_STUB_CONTENT}")
            endif()
        endforeach()

        file(REMOVE_RECURSE "${PYYGGDRASIL_PRIVATE_STUB_ROOT}")
    endif()

    file(GLOB_RECURSE PYYGGDRASIL_STUB_FILES "${PYYGGDRASIL_STUB_ROOT}/*.pyi")
    list(SORT PYYGGDRASIL_STUB_FILES)

    foreach(PYYGGDRASIL_STUB_FILE IN LISTS PYYGGDRASIL_STUB_FILES)
        pyyggdrasil_patch_stub_text("${PYYGGDRASIL_STUB_FILE}")
    endforeach()
endif()
