set(PYYGGDRASIL_STUB_ROOT "${CMAKE_INSTALL_PREFIX}/pyyggdrasil")

if(EXISTS "${PYYGGDRASIL_STUB_ROOT}")
    file(GLOB_RECURSE PYYGGDRASIL_STUB_FILES "${PYYGGDRASIL_STUB_ROOT}/*.pyi")

    foreach(PYYGGDRASIL_STUB_FILE IN LISTS PYYGGDRASIL_STUB_FILES)
        file(READ "${PYYGGDRASIL_STUB_FILE}" PYYGGDRASIL_STUB_CONTENT)
        set(PYYGGDRASIL_PATCHED_STUB_CONTENT "${PYYGGDRASIL_STUB_CONTENT}")

        string(REPLACE "pyyggdrasil._pyyggdrasil." "pyyggdrasil." PYYGGDRASIL_PATCHED_STUB_CONTENT "${PYYGGDRASIL_PATCHED_STUB_CONTENT}")
        string(REPLACE "pyyggdrasil._pyyggdrasil" "pyyggdrasil" PYYGGDRASIL_PATCHED_STUB_CONTENT "${PYYGGDRASIL_PATCHED_STUB_CONTENT}")

        if(NOT PYYGGDRASIL_STUB_CONTENT STREQUAL PYYGGDRASIL_PATCHED_STUB_CONTENT)
            file(WRITE "${PYYGGDRASIL_STUB_FILE}" "${PYYGGDRASIL_PATCHED_STUB_CONTENT}")
        endif()
    endforeach()
endif()
